name: httomolib
channels:
  - conda-forge
dependencies:
  - conda-forge::pillow>=9.5.0  
  - conda-forge::numpy  
  - conda-forge::scipy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::pytest-cov
  - conda-forge::pytest-mock
  - conda-forge::flake8
  - conda-forge::pyproject-flake8
  - conda-forge::pydocstyle
  - conda-forge::imageio
  - conda-forge::aiofiles
  - conda-forge::toml
  - conda-forge::setuptools-git-versioning
  - conda-forge::ipython
  - conda-forge::scikit-image

