{% set pyproject = load_file_data("../../pyproject.toml", from_recipe_dir=True) %}
{% set proj = pyproject.get("project") %}
{% set name = proj.get("name") %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG|trim("v") }}

source:
  path: ../../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning
  run:
    - python
    - numpy
    - setuptools
    - scipy
    - aiofiles
    - pytest-mock
    - pillow>=9.2.0
    - scikit-image
    - pytest

test:
  requires:
    - pip
    - pytest
  imports:
    - httomolib
    - httomolib.misc
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/DiamondLightSource/httomolib
  summary: 'A library of data processing and reconstruction methods for tomography'
  description: |
    A library of data processing and reconstruction methods for tomography

extra:
  recipe-maintainers:
    - namannimmo10
    - dkazanc
