name: HTTomolib doc test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
        - name: Checkout repository code
          uses: actions/checkout@v4

        - name: Setup Python 3.13
          uses: actions/setup-python@v4
          with:
            python-version: "3.13"

        - name: httomolib
          uses: mamba-org/setup-micromamba@v2
          with:
            environment-name: httomolib-docs
            environment-file: ./docs/source/doc-conda-requirements.yml
            post-cleanup: 'all'
            init-shell: bash

        - name: pip install dependencies
          run: |
            pip install standard-imghdr

        - name: Build api docs
          run: sphinx-apidoc -feT -t=./docs/source/_templates -o ./docs/source/api ./httomolib

        - name: Build html
          run: sphinx-build -a -E -b html ./docs/source/ ./docs/build/

        - name: Run ghp-import
          run: ghp-import -n -p -f ./docs/build
          env:
            GITHUB_TOKEN: ${{ github.token }}
