name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # setup Python 3.10
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # install dependencies with conda
      - name: Install dependencies with conda
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: httomolib
          environment-file: ./conda/environment.yml
          post-cleanup: 'all'
          init-shell: bash

      # install httomolib
      - name: Install httomolib
        run: |      
          pip install -e .
          micromamba list

      # run tests
      - name: Run CPU tests
        run: pytest
