name: httomolib tests and conda upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      # setup Python 3.9
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # install dependencies with conda
      - name: Install dependencies with conda
        run: |      
          $CONDA/bin/conda env update --file conda/environment.yml --name base
          pip install -e .
          $CONDA/bin/conda list

      # run tests
      - name: Run CPU tests
        run: |
          $CONDA/bin/conda install -c anaconda pytest
          pytest -m